# render.yaml
services:
  - type: web
    name: nextflex-cyber-shield
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
   